site_name: Functions-SDK for Python
theme:
  name: material
  font:
    text: Source Sans Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/branding_web_app_icon.png
  favicon: assets/branding_web_favicon.ico
  features:
    - content.code.copy
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/cslab/functions-sdk-python
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - link-marker


nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Concepts: key_concepts.md
  - Examples:
    - examples/index.md
    - examples/enforce_field_rules.md
    - examples/field_calculation.md
    - examples/workflows.md
    - examples/basic_report.md
  - Reference:
    - reference/events.md
    - reference/objects.md
    - reference/actions.md
    - reference/service.md
    - development_server.md
    - Python runtime: reference/runtime.md
  - Releases: release_notes.md
